console.log("Hello")

try {
    console.log("WE are Inside try  block");

    functionAdina()
}
catch (err) {
    console.log(err);
}finally{
console.log("Finally we will run this");
}
